services:
  - type: web
    name: mindease-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: mindease-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: AI_PROVIDER
        value: openai
      - key: DEBUG
        value: false

databases:
  - name: mindease-db
    databaseName: mindease
    user: mindease_user
    plan: free 